server:
  port: 6161
logging:
  file: elk-example.log
spring:
  application:
    name: address-service
  kafka:
    bootstrap-servers: 52.87.168.46:9092
eureka:
  instance:
    hostname: 172.31.89.106
    preferIpAddress: true
    statusPageUrl: http://${eureka.hostname}/info
    healthCheckUrl: http://${eureka.hostname}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.31.89.106:5151/eureka/