server:
  port: 6161
logging:
  file: elk-example.log
spring:
  application:
    name: address-service
  kafka:
    bootstrap-servers: 52.87.168.46:9092
eureka:
  instance:
    hostname: 34.227.104.40
    preferIpAddress: true
    statusPageUrl: http://${eureka.hostname}/infos
    healthCheckUrl: http://${eureka.hostname}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://34.227.104.40:5151/eureka/