server:
  port: 6161
logging:
  file: elk-example.log
spring:
  application:
    name: address-service
  kafka:
    bootstrap-servers: 52.87.168.46:9092
eureka:
  instance:
    hostname: ip-172-31-89-106.ec2.internal
    preferIpAddress: true
    statusPageUrl: http://${eureka.hostname}/info
    healthCheckUrl: http://${eureka.hostname}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ip-172-31-89-106.ec2.internal:5151/eureka/